spring:
  application:
    name: api-gateway

zuul:
  routes:
    web-apigateway:
      serviceId: web
      path: /api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
