spring:
  application:
    name: shop
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: ym
    password: 1234
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/