spring:
  application:
    name: shop
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: ym
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/