spring:
  application:
    name: shop-apigateway

zuul:
  routes:
    shop-apigateway:
      serviceId: shop
      path: /api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
